### ISSUE TITLE
Error extracting F/A-18 textures

### ISSUE THREAD

**Issue by leandroarndt** [leandroarndt/msfs_livery_tools#14]
```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "threading.py", line 1038, in _bootstrap_inner
  File "D:\Program Files (x86)\MSFS Livery Tools\msfs_livery_tools\gui\actions.py", line 29, in run
    self.task(*self.args, **self.kwargs)
  File "D:\Program Files (x86)\MSFS Livery Tools\msfs_livery_tools\gui\actions.py", line 145, in _do_extract_textures
    flags_dir.append(texture_dir.navigate(path))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files (x86)\MSFS Livery Tools\msfs_livery_tools\vfs\vfs.py", line 43, in navigate
    return self.parent.navigate(sep.join(parts))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files (x86)\MSFS Livery Tools\msfs_livery_tools\vfs\vfs.py", line 43, in navigate
    return self.parent.navigate(sep.join(parts))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files (x86)\MSFS Livery Tools\msfs_livery_tools\vfs\vfs.py", line 43, in navigate
    return self.parent.navigate(sep.join(parts))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 1 more time]
  File "D:\Program Files (x86)\MSFS Livery Tools\msfs_livery_tools\vfs\vfs.py", line 45, in navigate
    return self.contents[next_part.lower()].navigate(sep.join(parts))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files (x86)\MSFS Livery Tools\msfs_livery_tools\vfs\vfs.py", line 46, in navigate
    return self.contents[next_part]
           ~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'texture'
```

**Comment by leandroarndt** [comment]
Solved by edd170d896d6c373e45ba59dfd9808a09bcc1b92
